export const DeleteModalStyle = {
  overlay : {
    position        : 'fixed',
    top             : 0,
    left            : 0,
    right           : 0,
    bottom          : 0,
    backgroundColor : 'rgba(000, 000, 000, 0.6)',
    zIndex          : 10,
    display         : 'flex',
    justifyContent  : 'center',
    alignItems      : 'center',
  },

  content :  {
    position: 'relative',
    top: 0,
    left: 0,
    right: 0,
    bottom: 0,
    border: '1 solid rgb(204, 204, 204)',
    background: 'rgb(246, 246, 246)',
    overflow: 'auto',
    borderRadius: 4,
    outline: 'none',
    padding: 0,
    width: 600,
    height: 200,
    zIndex: 11,
    boxShadow: '0 4 20 rgba(0,0,0,.8)',
    fontSize: 13,
    display: 'flex',
    flexDirection: 'column',
}
};
